# Generated by Django 6.0.2 on 2026-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
