# Generated by Django 6.0.2 on 2026-02-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0002_rename_name_mentor_mentor_name_remove_mentor_id_and_more"),
        ("students", "0002_student_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentors.mentor",
            ),
        ),
    ]
