# Generated by Django 6.0.2 on 2026-02-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0003_alter_mentor_mentor_email_alter_mentor_mentor_id_and_more"),
        ("students", "0003_alter_student_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="mentors.mentor",
            ),
        ),
    ]
