# Generated by Django 6.0.2 on 2026-02-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
