# Generated by Django 6.0.2 on 2026-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField()),
                ("teacher_name", models.CharField(max_length=25)),
                ("teacher_email", models.EmailField(max_length=100)),
            ],
        ),
    ]
