# Generated by Django 6.0.2 on 2026-02-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="teacher_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="teacher_name",
            new_name="name",
        ),
    ]
