# Generated by Django 5.2.3 on 2026-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_alter_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
