# Generated by Django 6.0.2 on 2026-02-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mentor",
            old_name="name",
            new_name="mentor_name",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="id",
        ),
        migrations.AddField(
            model_name="mentor",
            name="mentor_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="mentor_id",
            field=models.CharField(
                default=12, max_length=25, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
