# Generated by Django 6.0.2 on 2026-02-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0002_rename_name_mentor_mentor_name_remove_mentor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="mentor_email",
            field=models.EmailField(default="General", max_length=254),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="mentor_id",
            field=models.CharField(
                default="General", max_length=25, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="mentor_name",
            field=models.CharField(default="General", max_length=25),
        ),
    ]
