# Generated by Django 6.0.2 on 2026-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0003_alter_mentor_mentor_email_alter_mentor_mentor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="mentor_expertise",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
